version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: ./server
    image: mevnstack_backend
    ports:
      - '3000:3000'
    links:
      - mongo-db

  client:
    build: ./client
    image: mevnstack_frontend
    ports:
      - '5080:80'
